### ISSUE TITLE
basic start up error

### ISSUE THREAD

**Issue by Poea** [SocketCluster/sc-phaser-sample#1]
npm ERR! EEXIST, mkdir '/root/speesmane/node_modules/socketcluster/node_modules/                                                                                                                                                             inquirer/node_modules/lodash'
File exists: /root/speesmane/node_modules/socketcluster/node_modules/inquirer/no                                                                                                                                                             de_modules/lodash
Move it away, and try again.

npm ERR! System Linux 3.16.0-25-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /root/speesmane
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! path /root/speesmane/node_modules/socketcluster/node_modules/inquirer/n                                                                                                                                                             ode_modules/lodash
npm ERR! fstream_path /root/speesmane/node_modules/socketcluster/node_modules/in                                                                                                                                                             quirer/node_modules/lodash/isArrayLike.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:171:23
npm ERR! fstream_stack /usr/lib/nodejs/mkdirp/index.js:46:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, open '/root/speesmane/node_modules/socketcluster/node_mo                                                                                                                                                             dules/inquirer/node_modules/rx/dist/rx.core.testing.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.16.0-25-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /root/speesmane
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! path /root/speesmane/node_modules/socketcluster/node_modules/inquirer/n                                                                                                                                                             ode_modules/rx/dist/rx.core.testing.js
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! spawn-sync@1.0.15 postinstall: `node postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the spawn-sync@1.0.15 postinstall script.
npm ERR! This is most likely a problem with the spawn-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls spawn-sync
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.16.0-25-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /root/speesmane
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! Error: ENOENT, lstat '/root/speesmane/node_modules/socketcluster/node_m                                                                                                                                                             odules/socketcluster-server/node_modules/uws/uws_darwin_48.node'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

**Comment by joseferben** [comment]
OS: macOS 10.12.2
node -v: 7.2.0
npm -v: 3.10.9

Works for me, did you try with a different node version?

**Comment by Poea** [comment]
issue was that my server wasnt running nodejs v6
